package Vista.Descuentos;

import Funciones.FuncionesDescuentos;
import Vista.Notificaciones.Aceptar_Cancelar;
import Vista.Notificaciones.Advertencia;
import Vista.Notificaciones.Fallo;
import Vista.Notificaciones.Realizado;
import java.awt.Frame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SwichBlade15
 */
public final class SeleccionarDescuentos extends javax.swing.JDialog {

    FuncionesDescuentos funcion = new FuncionesDescuentos();

    public SeleccionarDescuentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        rbtnClientes.doClick();
    }

    //Mostrar clientes por codigo
    public void mostrarClientesCodigo(String codigo) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarClientesDescuentosCedula(codigo);
            tblDescuentos.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //Mostrar clientes por nombre
    public void mostrarClientesNombre(String nombre) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarClientesDescuentosNombre(nombre);
            tblDescuentos.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
//********************FIN MOSTRAR CLIENTES**********************//

//********************MOSTRAR CATEGORIAS**********************//
    public void mostrarCategoriasCodigo(String codigo) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarCategoriasDescuentosCodigo(codigo);
            tblDescuentos.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void mostrarCategoriasNombre(String nombre) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarCategoriasDescuentosNombre(nombre);
            tblDescuentos.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
//********************FIN MOSTRAR CATEGORIAS**********************//    

//********************MOSTRAR PRODUCTOS**********************//
    //Mostrar productos por codigo
    public void mostrarProductosCodigo(String codigo) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarProductosDescuentosCodigo(codigo);
            tblDescuentos.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //Mostrar productos por nombre
    public void mostrarProductosNombre(String nombre) {
        try {
            DefaultTableModel modelo;
            modelo = funcion.mostrarProductosDescuentosNombre(nombre);
            tblDescuentos.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
//********************FIN MOSTRAR PRODUCTOS**********************//

    public void ocultar_columnas() {
        tblDescuentos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblDescuentos.getColumnModel().getColumn(0).setMinWidth(0);
        tblDescuentos.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngDescuentos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtnClientes = new javax.swing.JRadioButton();
        rbtnCategorias = new javax.swing.JRadioButton();
        rbtnProductos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDescuentos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Seleccionar Descuentos");

        rbtngDescuentos.add(rbtnClientes);
        rbtnClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnClientes.setText("Clientes");
        rbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClientesActionPerformed(evt);
            }
        });

        rbtngDescuentos.add(rbtnCategorias);
        rbtnCategorias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnCategorias.setText("Categorias");
        rbtnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCategoriasActionPerformed(evt);
            }
        });

        rbtngDescuentos.add(rbtnProductos);
        rbtnProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnProductos.setText("Productos");
        rbtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnProductosActionPerformed(evt);
            }
        });

        tblDescuentos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tblDescuentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDescuentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDescuentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDescuentos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnClientes)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rbtnCategorias)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnProductos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnClientes)
                    .addComponent(rbtnCategorias)
                    .addComponent(rbtnProductos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClientesActionPerformed
        mostrarClientesCodigo("");
    }//GEN-LAST:event_rbtnClientesActionPerformed

    private void rbtnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCategoriasActionPerformed
        mostrarCategoriasCodigo("");
    }//GEN-LAST:event_rbtnCategoriasActionPerformed

    private void rbtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnProductosActionPerformed
        mostrarProductosCodigo("");
    }//GEN-LAST:event_rbtnProductosActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        if (rbtnClientes.isSelected()) {
            mostrarClientesCodigo(txtCodigo.getText());
        } else if (rbtnCategorias.isSelected()) {
            mostrarCategoriasCodigo(txtCodigo.getText());
        } else if (rbtnProductos.isSelected()) {
            mostrarProductosCodigo(txtCodigo.getText());
        }
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if (rbtnClientes.isSelected()) {
            mostrarClientesNombre(txtNombre.getText());
        } else if (rbtnCategorias.isSelected()) {
            mostrarCategoriasNombre(txtNombre.getText());
        } else if (rbtnProductos.isSelected()) {
            mostrarProductosNombre(txtNombre.getText());
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void tblDescuentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDescuentosMouseClicked
        int seleccionar = tblDescuentos.rowAtPoint(evt.getPoint());

        if (evt.getClickCount() == 2) {
            Descuentos.txtIddetalledescuentos.setText(String.valueOf(tblDescuentos.getValueAt(seleccionar, 0)));
            Descuentos.txtAplicar.setText(String.valueOf(tblDescuentos.getValueAt(seleccionar, 1)));
            Descuentos.txtCodigo.setText(String.valueOf(tblDescuentos.getValueAt(seleccionar, 0)));
            

            if (rbtnClientes.isSelected()) {
                Descuentos.txtTipo.setText("Clientes");
            } else if (rbtnCategorias.isSelected()) {
                Descuentos.txtTipo.setText("Categorias");
            } else if (rbtnProductos.isSelected()) {
                Descuentos.txtTipo.setText("Productos");
            }

            dispose();
        }
    }//GEN-LAST:event_tblDescuentosMouseClicked

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        txtCodigo.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        txtCodigo.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarDescuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            SeleccionarDescuentos dialog = new SeleccionarDescuentos(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    //Metodos para llamar a los JDialog de Advertencia, Fallo y Realizado
    Frame f = JOptionPane.getFrameForComponent(this);
    String mensaje;
    String encabezado;
    Icon icono;

    public void advertencia() {
        Advertencia dialog = new Advertencia(f, true);
        Advertencia.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void fallo() {
        Fallo dialog = new Fallo(f, true);
        Fallo.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void realizado() {
        Realizado dialog = new Realizado(f, true);
        Realizado.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void aceptarCancelar() {
        Aceptar_Cancelar dialog = new Aceptar_Cancelar(f, true);
        icono = new ImageIcon(getClass().getResource("/Imagenes/FondoCerrarSesion.png"));
        Aceptar_Cancelar.lblFondo.setIcon(icono);
        Aceptar_Cancelar.lblEncabezado.setText(encabezado);
        Aceptar_Cancelar.lblMensaje.setText(mensaje);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnCategorias;
    private javax.swing.JRadioButton rbtnClientes;
    private javax.swing.JRadioButton rbtnProductos;
    private javax.swing.ButtonGroup rbtngDescuentos;
    private javax.swing.JTable tblDescuentos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
